[package]
name = "boids"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release-with-debug]
inherits = "release"
debug = true

[dependencies]
bevy = "0.16.0"
bevy_egui = "0.34.1"
itertools = "0.14.0"
rand = "0.8.5"
