[unstable]
codegen-backend = true

# [profile.dev]
# codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

# [target.x86_64-unknown-linux-gnu]
# linker = "/usr/bin/clang"
# rustflags = [
#     "-C",
#     "link-arg=--ld-path=/usr/bin/mold",
#     "-Clink-arg=-Wl,--no-rosegment",    # For flamegrpah
#     "-Zshare-generics=y",
#     # "-C", "codegen-backend=cranelift"
# ]
