[unstable]
codegen-backend = true

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
   "-C", "link-arg=--ld-path=/usr/bin/mold",
  # "-C", "codegen-backend=cranelift"
]